name: 'conventional-release-labels'
description: 'automatically apply release labels to PR, based on conventionalcommits.org'
author: Google LLC
inputs:
  token:
    description: 'GitHub token for applying labels, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  feature_label:
    description: 'label applied to feature pull requests'
    required: false
    default: feature

runs:
  using: 'node14'
  main: 'dist/index.js'
